name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.14]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: yarn install
      - run: yarn run test
      - run: yarn run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          files: ./clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
